# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portofol',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
