# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0002_auto_20170507_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portofol',
            options={'ordering': ['-timestamp', '-updated']},
        ),
    ]
