# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 22:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0003_auto_20170507_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='portofol',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2017, 5, 7, 22, 29, 35, 749260, tzinfo=utc), unique=True),
            preserve_default=False,
        ),
    ]
