# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import portofolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0004_portofol_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portofol',
            name='image',
            field=models.ImageField(upload_to=portofolio.models.upload_location),
        ),
    ]
